In [1]:
import torch

In [3]:
test=torch.rand(3,4)
test

tensor([[0.4381, 0.0094, 0.0135, 0.6712],
        [0.8440, 0.7473, 0.8041, 0.5846],
        [0.3086, 0.2212, 0.4700, 0.6426]])

In [2]:
a=torch.rand((3,4))
a

tensor([[0.7880, 0.3966, 0.9084, 0.0189],
        [0.0559, 0.3199, 0.3886, 0.9910],
        [0.8741, 0.1385, 0.7851, 0.4506]])

In [5]:
out=torch.chunk(a,2,dim=0)
print(out)
print(out[0].shape)
print(out[1].shape)

(tensor([[0.7880, 0.3966, 0.9084, 0.0189],
        [0.0559, 0.3199, 0.3886, 0.9910]]), tensor([[0.8741, 0.1385, 0.7851, 0.4506]]))
torch.Size([2, 4])
torch.Size([1, 4])


torch.split

In [9]:
out2=torch.split(a,2,dim=1)
print(out2)
print(out2[0].shape)

(tensor([[0.7880, 0.3966],
        [0.0559, 0.3199],
        [0.8741, 0.1385]]), tensor([[0.9084, 0.0189],
        [0.3886, 0.9910],
        [0.7851, 0.4506]]))
torch.Size([3, 2])


In [10]:
out2=torch.split(a,3,dim=0)

In [11]:
s=torch.rand((10,4))
s

tensor([[0.4460, 0.6099, 0.8700, 0.6059],
        [0.5930, 0.2394, 0.6488, 0.5360],
        [0.5845, 0.1175, 0.5859, 0.9519],
        [0.5137, 0.8470, 0.9140, 0.0745],
        [0.7564, 0.4195, 0.4373, 0.8356],
        [0.0736, 0.3076, 0.2985, 0.3600],
        [0.0351, 0.0730, 0.2538, 0.2072],
        [0.3462, 0.6626, 0.4955, 0.4599],
        [0.7538, 0.0349, 0.9599, 0.9336],
        [0.3639, 0.8122, 0.3002, 0.1343]])

In [12]:
sout=torch.split(s,3,dim=0)
print(sout)

(tensor([[0.4460, 0.6099, 0.8700, 0.6059],
        [0.5930, 0.2394, 0.6488, 0.5360],
        [0.5845, 0.1175, 0.5859, 0.9519]]), tensor([[0.5137, 0.8470, 0.9140, 0.0745],
        [0.7564, 0.4195, 0.4373, 0.8356],
        [0.0736, 0.3076, 0.2985, 0.3600]]), tensor([[0.0351, 0.0730, 0.2538, 0.2072],
        [0.3462, 0.6626, 0.4955, 0.4599],
        [0.7538, 0.0349, 0.9599, 0.9336]]), tensor([[0.3639, 0.8122, 0.3002, 0.1343]]))


In [15]:
s2=torch.split(s,[1,3,6],dim=0)
print(s2)
for i in s2:
    print(i.shape)


(tensor([[0.4460, 0.6099, 0.8700, 0.6059]]), tensor([[0.5930, 0.2394, 0.6488, 0.5360],
        [0.5845, 0.1175, 0.5859, 0.9519],
        [0.5137, 0.8470, 0.9140, 0.0745]]), tensor([[0.7564, 0.4195, 0.4373, 0.8356],
        [0.0736, 0.3076, 0.2985, 0.3600],
        [0.0351, 0.0730, 0.2538, 0.2072],
        [0.3462, 0.6626, 0.4955, 0.4599],
        [0.7538, 0.0349, 0.9599, 0.9336],
        [0.3639, 0.8122, 0.3002, 0.1343]]))
torch.Size([1, 4])
torch.Size([3, 4])
torch.Size([6, 4])
