In [28]:
# house price data source http://t.cn/RfHTAgY
# https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data

# handle writer character identify
# data source
# http://yann.lecun.com/exdb/mnist/

In [29]:
import wget
import os
import torch

In [30]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
output_path = "./housing.data"

# Check if the file already exists
if not os.path.exists(output_path):
    print(f"Downloading housing data from {url}...")
    wget.download(url, output_path)
    print("\nDownload complete!")
else:
    print(f"File {output_path} already exists.")

File ./housing.data already exists.


In [31]:
import numpy as np
import re
ff=open("housing.data").readlines()
data=[]
for item in ff:
    out=re.sub(r"\s{2,}"," ",item).strip()
    print(out)
    data.append(out.split(" "))
data=np.array(data).astype(float)    
print(data)
print(data.shape)

0.00632 18.00 2.310 0 0.5380 6.5750 65.20 4.0900 1 296.0 15.30 396.90 4.98 24.00
0.02731 0.00 7.070 0 0.4690 6.4210 78.90 4.9671 2 242.0 17.80 396.90 9.14 21.60
0.02729 0.00 7.070 0 0.4690 7.1850 61.10 4.9671 2 242.0 17.80 392.83 4.03 34.70
0.03237 0.00 2.180 0 0.4580 6.9980 45.80 6.0622 3 222.0 18.70 394.63 2.94 33.40
0.06905 0.00 2.180 0 0.4580 7.1470 54.20 6.0622 3 222.0 18.70 396.90 5.33 36.20
0.02985 0.00 2.180 0 0.4580 6.4300 58.70 6.0622 3 222.0 18.70 394.12 5.21 28.70
0.08829 12.50 7.870 0 0.5240 6.0120 66.60 5.5605 5 311.0 15.20 395.60 12.43 22.90
0.14455 12.50 7.870 0 0.5240 6.1720 96.10 5.9505 5 311.0 15.20 396.90 19.15 27.10
0.21124 12.50 7.870 0 0.5240 5.6310 100.00 6.0821 5 311.0 15.20 386.63 29.93 16.50
0.17004 12.50 7.870 0 0.5240 6.0040 85.90 6.5921 5 311.0 15.20 386.71 17.10 18.90
0.22489 12.50 7.870 0 0.5240 6.3770 94.30 6.3467 5 311.0 15.20 392.52 20.45 15.00
0.11747 12.50 7.870 0 0.5240 6.0090 82.90 6.2267 5 311.0 15.20 396.90 13.27 18.90
0.09378 12.50 7.870 0 0.52

In [32]:
Y=data[:,-1]
print(Y)
print(Y.shape)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [33]:
X=data[:,0:-1]
print(X)
print(X.shape)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
(506, 13)


In [34]:
X_train=X[0:496,...]
Y_train=Y[0:496,...]

In [35]:
X_test=X[496:,...]
Y_test=Y[496:,...]

In [36]:
print(X_train.shape)

(496, 13)


In [37]:
print(Y_train.shape)

(496,)


In [38]:
print(X_test.shape)

(10, 13)


In [39]:
print(Y_test.shape)

(10,)


In [40]:
class Net(torch.nn.Module):
    def __init__(self,n_feature,n_output):
        super(Net,self).__init__()
        self.hidden=torch.nn.Linear(n_feature,100)
        self.predict=torch.nn.Linear(100,n_output)
        
    def forward(self,x):
        out=self.hidden(x)
        out=torch.relu(out)
        out=self.predict(out)
        return out
net=Net(13,1)

#loss
loss_func=torch.nn.MSELoss()

#optimiter

optimizer=torch.optim.Adam(net.parameters(),lr=0.01)

#training

for i in range(10000):
    x_data=torch.tensor(X_train,dtype=torch.float32)
    y_data=torch.tensor(Y_train,dtype=torch.float32)
    
    pred=net.forward(x_data)
    pred=torch.squeeze(pred)
    loss=loss_func(pred,y_data)*0.001
    # print(pred.shape)
    # print(y_data.shape)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print("it:{} loss_train:{}".format(i,loss))
    print(pred[0:10])
    print(y_data[0:10])
    
    



     

it:0 loss_train:0.13004323840141296
tensor([25.9252, 21.9704, 23.2447, 23.5417, 23.0012, 22.6197, 24.2549, 21.4132,
        19.8693, 21.5241], grad_fn=<SliceBackward0>)
tensor([24.0000, 21.6000, 34.7000, 33.4000, 36.2000, 28.7000, 22.9000, 27.1000,
        16.5000, 18.9000])
it:1 loss_train:3.012951135635376
tensor([79.2797, 73.6400, 73.6668, 72.4340, 72.4689, 71.9510, 78.9144, 77.5120,
        75.5645, 76.4427], grad_fn=<SliceBackward0>)
tensor([24.0000, 21.6000, 34.7000, 33.4000, 36.2000, 28.7000, 22.9000, 27.1000,
        16.5000, 18.9000])
it:2 loss_train:0.29007938504219055
tensor([42.3415, 38.1328, 39.0525, 38.8482, 38.5175, 38.0837, 41.2982, 38.8159,
        37.0918, 38.5235], grad_fn=<SliceBackward0>)
tensor([24.0000, 21.6000, 34.7000, 33.4000, 36.2000, 28.7000, 22.9000, 27.1000,
        16.5000, 18.9000])
it:3 loss_train:0.7568742632865906
tensor([ 4.6155,  2.4463,  4.3353,  5.1233,  4.3255,  3.9904,  2.7740, -0.4078,
        -1.8709,  0.2103], grad_fn=<SliceBackward0>)
tensor

In [41]:
#test
x_data=torch.tensor(X_test,dtype=torch.float32)
y_data=torch.tensor(Y_test,dtype=torch.float32)
pred=net.forward(x_data)
pred=torch.squeeze(pred)
loss_test=loss_func(pred,y_data)*0.001
print("ite:{},loss_test:{}".format(i,loss_test))


ite:9999,loss_test:0.008580923080444336


In [ ]:
torch.save(net,"./model/model.pkl")
#use torch .load to load model

In [ ]:
torch.save(net.state_dict(),"params.pkl")

In [ ]:
net.load_state_dict(torch.load("params.pkl"))