In [1]:
import torch

In [12]:
a=torch.rand((2,3))
a

tensor([[0.9060, 0.3667, 0.6040],
        [0.3112, 0.3242, 0.8243]])

In [14]:
b=torch.reshape(a,(3,2))
b

tensor([[0.9060, 0.3667],
        [0.6040, 0.3112],
        [0.3242, 0.8243]])

In [15]:
c=torch.t(b)
c

tensor([[0.9060, 0.6040, 0.3242],
        [0.3667, 0.3112, 0.8243]])

In [17]:
d=torch.transpose(c,0,1)
d

tensor([[0.9060, 0.3667],
        [0.6040, 0.3112],
        [0.3242, 0.8243]])

In [18]:
e=torch.rand(1,2,3)
e

tensor([[[0.2122, 0.1604, 0.6851],
         [0.9400, 0.2967, 0.1987]]])

In [20]:
f=torch.transpose(e,0,1)
f

tensor([[[0.2122, 0.1604, 0.6851]],

        [[0.9400, 0.2967, 0.1987]]])

In [21]:
f.shape

torch.Size([2, 1, 3])

https://pytorch.org/docs/2.6/generated/torch.squeeze.html

In [22]:
g=torch.squeeze(f)
g.shape

torch.Size([2, 3])

In [23]:
h=torch.unsqueeze(f,-1)
h

tensor([[[[0.2122],
          [0.1604],
          [0.6851]]],


        [[[0.9400],
          [0.2967],
          [0.1987]]]])

In [24]:
h.shape

torch.Size([2, 1, 3, 1])

In [26]:
i=torch.unbind(a,dim=1)
i

(tensor([0.9060, 0.3112]), tensor([0.3667, 0.3242]), tensor([0.6040, 0.8243]))

https://pytorch.org/docs/stable/generated/torch.unbind.html

In [29]:
a

tensor([[0.9060, 0.3667, 0.6040],
        [0.3112, 0.3242, 0.8243]])

In [33]:
a.shape

torch.Size([2, 3])

https://pytorch.org/docs/stable/generated/torch.flip.html

In [32]:
l=torch.flip(a,dims=[0])
l

tensor([[0.3112, 0.3242, 0.8243],
        [0.9060, 0.3667, 0.6040]])

https://pytorch.org/docs/stable/generated/torch.rot90.html

In [34]:
m=torch.rot90(a)
m

tensor([[0.6040, 0.8243],
        [0.3667, 0.3242],
        [0.9060, 0.3112]])

In [35]:
m.shape

torch.Size([3, 2])