In [2]:
import torch

In [8]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print("a:",a)
# print(a)
print("b:",b)
#print(b)
print("a+b",a+b)

print("a.add(b)",a.add(b))
print("torch.add(a,b)",torch.add(a,b))
print("a:",a)
print("a.add_(b)",a.add_(b))
print("a:",a)


a: tensor([[0.6229, 0.4140, 0.1336],
        [0.5600, 0.1523, 0.8041]])
b: tensor([[0.9023, 0.7601, 0.9825],
        [0.1966, 0.0446, 0.4453]])
a+b tensor([[1.5253, 1.1740, 1.1160],
        [0.7566, 0.1969, 1.2494]])
a.add(b) tensor([[1.5253, 1.1740, 1.1160],
        [0.7566, 0.1969, 1.2494]])
torch.add(a,b) tensor([[1.5253, 1.1740, 1.1160],
        [0.7566, 0.1969, 1.2494]])
a: tensor([[0.6229, 0.4140, 0.1336],
        [0.5600, 0.1523, 0.8041]])
a.add_(b) tensor([[1.5253, 1.1740, 1.1160],
        [0.7566, 0.1969, 1.2494]])
a: tensor([[1.5253, 1.1740, 1.1160],
        [0.7566, 0.1969, 1.2494]])


In [10]:
#sub
print("a-b",a-b)
print(torch.sub(a,b))
print("a.sub(b)",a.sub(b))
print("a.sub_(b)",a.sub_(b))
print("a:",a)

a-b tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
a.sub(b) tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
a.sub_(b) tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
a: tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])


In [11]:
## mul
print("a*b",a*b)
print(torch.mul(a,b))
print("a.mul(b)",a.mul(b))
print("a.mul_(b)",a.mul_(b))    
print("a:",a)

a*b tensor([[-0.2521, -0.2630, -0.8340],
        [ 0.0714,  0.0048,  0.1598]])
tensor([[-0.2521, -0.2630, -0.8340],
        [ 0.0714,  0.0048,  0.1598]])
a.mul(b) tensor([[-0.2521, -0.2630, -0.8340],
        [ 0.0714,  0.0048,  0.1598]])
a.mul_(b) tensor([[-0.2521, -0.2630, -0.8340],
        [ 0.0714,  0.0048,  0.1598]])
a: tensor([[-0.2521, -0.2630, -0.8340],
        [ 0.0714,  0.0048,  0.1598]])


In [12]:
print("====div===")
print("a/b",a/b)
print(torch.div(a,b))
print("a.div(b)",a.div(b))
print("a.div_(b)",a.div_(b))
print("a:",a)

====div===
a/b tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
a.div(b) tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
a.div_(b) tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])
a: tensor([[-0.2794, -0.3461, -0.8489],
        [ 0.3634,  0.1077,  0.3588]])


In [13]:
###matrix mul
print("====matmul===")
a=torch.ones(2,1)
b=torch.ones(1,2)
print(a @ b)
print(a.matmul(b))
print(torch.matmul(a,b))
print(torch.mm(a,b))
print("a:",a)


====matmul===
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
a: tensor([[1.],
        [1.]])


In [ ]:
#必须保证最后两个维度能进行矩阵运算
a=torch.ones(1,2,3,4)
print(a)
b=torch.ones(1,2,4,3)
print(b)
print(a.matmul(b).shape)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
torch.Size([1, 2, 3, 3])


In [21]:
##power
print("====power===")
a=torch.tensor([1,2])
print("a:",a)
print("a size",a.size())
print(torch.pow(a,3))
print(a**3)
print(a.pow_(3))
print("a:",a)



====power===
a: tensor([1, 2])
a size torch.Size([2])
tensor([1, 8])
tensor([1, 8])
tensor([1, 8])
a: tensor([1, 8])


In [25]:
#exp
a=torch.tensor([1,2],dtype=torch.float32)
print(a.type())
print(torch.exp(a))
print(torch.exp_(a))
print(a.exp())
print(a.exp_())
print("a:",a)

torch.FloatTensor
tensor([2.7183, 7.3891])
tensor([2.7183, 7.3891])
tensor([  15.1543, 1618.1781])
tensor([  15.1543, 1618.1781])
a: tensor([  15.1543, 1618.1781])


In [27]:
##log
a=torch.tensor([10,2],dtype=torch.float32)
print(torch.log(a))
print(torch.log_(a))
print(a.log())
print(a.log_())


tensor([2.3026, 0.6931])
tensor([2.3026, 0.6931])
tensor([ 0.8340, -0.3665])
tensor([ 0.8340, -0.3665])


In [29]:
##sqrt
a=torch.tensor([10,2],dtype=torch.float32)
print(torch.sqrt(a))
print(torch.sqrt_(a))
print(a.sqrt())
print(a.sqrt_())    



tensor([3.1623, 1.4142])
tensor([3.1623, 1.4142])
tensor([1.7783, 1.1892])
tensor([1.7783, 1.1892])
