In [1]:
import torch

In [3]:
a=torch.rand(2,2)*10
a

tensor([[1.7075, 5.0797],
        [6.0114, 1.3764]])

In [ ]:
b=a.clamp(1,10)
b

tensor([[1.7075, 5.0797],
        [6.0114, 1.3764]])

In [6]:
c=a.clamp(1,2)
c

tensor([[1.7075, 2.0000],
        [2.0000, 1.3764]])

In [7]:
d=a.clamp(2,5)
d

tensor([[2., 5.],
        [5., 2.]])