In [1]:
import torch

In [2]:
a=torch.rand(2,2)
a

tensor([[0.0353, 0.6250],
        [0.4666, 0.6279]])

In [ ]:
torch.mean(a)

tensor(0.4387)

In [6]:
torch.mean(a,dim=0)

tensor([0.2510, 0.6264])

In [ ]:
torch.sum(a)

tensor(1.7548)

In [7]:
torch.sum(a,dim=0)

tensor([0.5019, 1.2529])

In [ ]:
#累积
torch.prod(a)

tensor(0.0065)

In [8]:
torch.prod(a,dim=0)

tensor([0.0165, 0.3924])

arxmax, argmin打印的是维度上的索引值

In [9]:
torch.argmax(a)

tensor(3)

In [10]:
torch.argmax(a,dim=0)

tensor([1, 1])

In [11]:
torch.argmin(a)

tensor(0)

In [12]:
torch.argmin(a,dim=0)

tensor([0, 0])

In [14]:
# 标准差
torch.std(a)

tensor(0.2793)

In [15]:
# 方差
torch.var(a)

tensor(0.0780)

In [16]:
# 中位数
torch.median(a)

tensor(0.4666)

torch.mode返回一个namedtuple（值、索引），其中值是给定维度dim中输入张量每行的模式值，即该行中最常出现的值，索引是找到的每个模式值的索引位置。


In [17]:
torch.mode(a)

torch.return_types.mode(
values=tensor([0.0353, 0.4666]),
indices=tensor([0, 0]))

https://pytorch.org/docs/stable/generated/torch.histc.html
直方图

In [20]:
b=torch.rand(2,2)*10
print(b)
torch.histc(b,6,0,0)

tensor([[1.4735, 4.2930],
        [2.4474, 0.3637]])


tensor([1., 1., 0., 1., 0., 1.])

torch.bincount 打印每个数的出现频次，bincount只能处理一维的tensor

In [22]:
c=torch.randint(0,10,[10])
print(c)
print(torch.bincount(c, minlength=10))

tensor([8, 9, 0, 2, 1, 4, 2, 9, 8, 0])
tensor([2, 1, 2, 0, 1, 0, 0, 0, 2, 2])
