In [ ]:
# 经常会用到的tensor
import torch

In [2]:
a=torch.Tensor([[1,2],[3,4]])
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [3]:
a.type()

'torch.FloatTensor'

In [4]:
ab=torch.Tensor(2,3)
ab


tensor([[6.9537e+18, 1.7446e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
ab.type()

'torch.FloatTensor'

In [7]:
a=torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [8]:
b=torch.eye(2,2)
b

tensor([[1., 0.],
        [0., 1.]])

In [12]:
c=torch.zeros(2,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
d=torch.zeros_like(c)
d

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
e=torch.rand(2,2)
e

tensor([[0.4775, 0.7430],
        [0.1454, 0.2530]])

In [16]:
e.type()

'torch.FloatTensor'

正态分布

In [31]:
f=torch.normal(mean=0.0,std=torch.rand(5))
print(f.type())
f

torch.FloatTensor


tensor([-0.0570,  0.1396,  0.0273, -0.8303, -1.3907])

均匀分布

In [30]:
g=torch.Tensor(2,2).uniform_(-1,1)
print(g.type())
g

torch.FloatTensor


tensor([[-0.8821,  0.6754],
        [-0.2329, -0.9101]])

In [23]:
h=torch.arange(0,10,2)
print(h)
h.type()

tensor([0, 2, 4, 6, 8])


'torch.LongTensor'

In [29]:
# 拿到等间隔的n个数
i=torch.linspace(2,10,4)
print(i.type())
i

torch.FloatTensor


tensor([ 2.0000,  4.6667,  7.3333, 10.0000])

In [28]:
# 输出打乱的序列
j=torch.randperm(10)
print(j.type())
j

torch.LongTensor


tensor([9, 7, 8, 2, 5, 0, 3, 6, 1, 4])

In [32]:
import numpy as np
hi=np.array([[1,2],[3,4]])
hi

array([[1, 2],
       [3, 4]])