In [2]:
import torch

In [3]:
a=torch.rand(4,4)
b=torch.rand(4,4)
c=torch.rand(2,2)

In [4]:
print(a)
print(b)
print(c)

tensor([[0.6344, 0.6355, 0.0711, 0.5574],
        [0.5687, 0.9394, 0.6344, 0.3757],
        [0.0485, 0.5267, 0.6287, 0.0268],
        [0.7314, 0.3236, 0.9564, 0.6042]])
tensor([[0.6053, 0.3222, 0.6831, 0.1237],
        [0.1686, 0.6469, 0.3500, 0.7743],
        [0.8509, 0.4268, 0.3531, 0.3599],
        [0.6420, 0.0966, 0.0741, 0.1882]])
tensor([[0.0273, 0.2676],
        [0.8879, 0.9295]])


In [5]:
out=torch.where(a>0.5,a,b)
out

tensor([[0.6344, 0.6355, 0.6831, 0.5574],
        [0.5687, 0.9394, 0.6344, 0.7743],
        [0.8509, 0.5267, 0.6287, 0.3599],
        [0.7314, 0.0966, 0.9564, 0.6042]])

torch.index_select

In [6]:
#取第0，3，2行
torch.index_select(a,dim=0,index=torch.tensor([0,3,2]))


tensor([[0.6344, 0.6355, 0.0711, 0.5574],
        [0.7314, 0.3236, 0.9564, 0.6042],
        [0.0485, 0.5267, 0.6287, 0.0268]])

First, torch.linspace(1, 16, steps=16) generates a 1-dimensional tensor containing 16 values equally spaced between 1 and 16 (inclusive). This creates the sequence [1, 2, 3, ..., 16].

Then, the .view(4, 4) method reshapes this 1D tensor into a 2D tensor with 4 rows and 4 columns. The result is a 4x4 matrix where the values are arranged in row-major order:

In [7]:
d=torch.linspace(1, 16, steps=16).view(4, 4)
d

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

https://pytorch.org/docs/stable/generated/torch.gather.html
解释：
https://stackoverflow.com/questions/50999977/what-does-gather-do-in-pytorch-in-layman-terms

In [8]:
e=torch.gather(d,dim=0,index=torch.tensor([[0,1,1,1],
                                           [0,1,2,2],
                                           [0,1,3,3]
                                           ]))
e

tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])

In [9]:
e.shape

torch.Size([3, 4])

torch.mask

In [10]:
mask=torch.gt(d,8)
mask
# torch.masked_select(d,)

tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [11]:
d

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [12]:
torch.masked_select(d,mask)

tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])

In [13]:
#torch.take
f=torch.take(d,index=torch.tensor([0,15,13,10]))
f

tensor([ 1., 16., 14., 11.])

In [14]:
#torch.nonzero
g=torch.tensor([[0,1,2,0],[2,3,0,1]])
h=torch.nonzero(g)
h

tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])