In [1]:
import torch

In [2]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [3]:
torch.eq(a,b)

tensor([[False, False, False],
        [False, False, False]])

In [4]:
torch.equal(a,b)

False

In [5]:
torch.ge(a,b)

tensor([[False,  True, False],
        [False,  True,  True]])

In [6]:
torch.gt(a,b)

tensor([[False,  True, False],
        [False,  True,  True]])

In [7]:
torch.le(a,b)

tensor([[ True, False,  True],
        [ True, False, False]])

In [8]:
torch.lt(a,b)

tensor([[ True, False,  True],
        [ True, False, False]])

In [9]:
torch.ne(a,b)

tensor([[True, True, True],
        [True, True, True]])

In [10]:
c=torch.ones(2,3)
d=torch.ones(2,3)
torch.eq(c,d)

tensor([[True, True, True],
        [True, True, True]])

不同shape,无法比较

In [ ]:
e=torch.ones(2,3)
f=torch.ones(2,4)
# torch.eq(e,f)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

#https://pytorch.org/docs/stable/generated/torch.sort.html

In [ ]:
g=torch.tensor([[1,4,4,3,5],[2,1,3,4,5]])
print(g.shape)
sorted_tensor, sorted_indices = torch.sort(g, dim=1)
print(sorted_tensor)
print(sorted_indices)

torch.Size([2, 5])


torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [1, 2, 3, 4, 5]]),
indices=tensor([[0, 3, 1, 2, 4],
        [1, 0, 2, 3, 4]]))

## topk

In [27]:
h=torch.tensor([[2,4,3,1,5],[2,3,5,1,4]])
print(h.shape)

torch.Size([2, 5])


In [30]:
torch.topk(h,k=1,dim=0)

torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5]]),
indices=tensor([[0, 0, 1, 0, 0]]))

In [31]:
torch.topk(h,k=1,dim=1)

torch.return_types.topk(
values=tensor([[5],
        [5]]),
indices=tensor([[4],
        [2]]))

In [32]:
torch.topk(h,k=2,dim=1)

torch.return_types.topk(
values=tensor([[5, 4],
        [5, 4]]),
indices=tensor([[4, 1],
        [2, 4]]))

In [34]:
print(torch.kthvalue(h,k=2,dim=0))

torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))


#https://pytorch.org/docs/stable/generated/torch.kthvalue.html

In [40]:
print(torch.kthvalue(h,k=2,dim=1))

torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


https://pytorch.org/docs/stable/generated/torch.isfinite.html
</br>
finite: 有限的

https://pytorch.org/docs/stable/generated/torch.isinf.html

infinite:无穷大

In [42]:
ab=torch.rand(2,3)
print(ab)
print(torch.isfinite(ab))
print(torch.isfinite(ab/0))
print(torch.isinf(ab/0))
print(torch.isnan(ab/0))


tensor([[0.5425, 0.3321, 0.7756],
        [0.6893, 0.5648, 0.4632]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])


In [43]:
import numpy as np
a=torch.tensor([1,2,np.nan])
print(torch.isnan(a))

tensor([False, False,  True])
