In [1]:
import torch


In [2]:
a=torch.rand(2,2)
a=a*10
a

tensor([[0.6529, 2.6689],
        [4.5054, 3.1992]])

In [3]:
a.to(torch.float)

tensor([[0.6529, 2.6689],
        [4.5054, 3.1992]])

In [4]:
torch.ceil(a)

tensor([[1., 3.],
        [5., 4.]])

In [5]:
torch.round(a)

tensor([[1., 3.],
        [5., 3.]])

In [6]:
torch.trunc(a)

tensor([[0., 2.],
        [4., 3.]])

In [7]:
torch.frac(a)

tensor([[0.6529, 0.6689],
        [0.5054, 0.1992]])

In [8]:
a%2

tensor([[0.6529, 0.6689],
        [0.5054, 1.1992]])