In [1]:
import torch


In [3]:
a=torch.rand(2,3)
b=torch.rand(3)
c=a+b
c

tensor([[0.8222, 1.1515, 1.3028],
        [0.7967, 1.1723, 1.3030]])

In [4]:
a

tensor([[0.5437, 0.9451, 0.4122],
        [0.5182, 0.9659, 0.4123]])

In [5]:
b

tensor([0.2785, 0.2064, 0.8906])

a: 2*3<br>
b: 1*3<br>
c: 2*3<br>

c取每一列中的最大值

In [6]:
c.shape

torch.Size([2, 3])