In [9]:
import torch
import numpy as np
import cv2

In [10]:
a=np.zeros([2,2])
a

array([[0., 0.],
       [0., 0.]])

In [11]:
out=torch.from_numpy(a)

In [12]:
print(out)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [13]:
im_data=open("./test.png")

In [14]:
# Read the image file as a NumPy array
image = cv2.imread("./test.png")

# Display the image
cv2.imshow("test", image)
cv2.waitKey(0)


-1

In [16]:
out=torch.from_numpy(image)
out

tensor([[[253, 253, 253],
         [254, 254, 254],
         [254, 254, 254],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[254, 254, 254],
         [253, 253, 253],
         [252, 252, 252],
         ...,
         [252, 252, 252],
         [253, 253, 253],
         [255, 255, 255]],

        [[254, 254, 254],
         [252, 252, 252],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [252, 252, 252],
         [255, 255, 255]],

        ...,

        [[255, 255, 255],
         [252, 252, 252],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [255, 255, 255],
         [255, 254, 255]],

        [[255, 255, 255],
         [254, 254, 254],
         [252, 252, 252],
         ...,
         [255, 252, 255],
         [254, 252, 254],
         [255, 254, 255]],

        [[255, 255, 255],
         [254, 254, 254],
         [255, 255, 255],
         ...,
         [255, 254, 255],
        

In [17]:
out=torch.flip(out,dims=[0])
cv2.imshow("test2", out.numpy())
cv2.waitKey(0)

-1