In [1]:
import torch

In [2]:
a=torch.zeros((2,4))

b=torch.ones((2,4))

print(a)
print(b)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [3]:
out=torch.cat((a,b),dim=0)
out

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [4]:
out2=torch.cat((a,b),dim=1)
out2

tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])

torch.stack

In [5]:
a=torch.linspace(1,6,6).view(2,3)
b=torch.linspace(7,12,6).view(2,3)
print(a,b)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
out3=torch.stack((a,b),dim=0)
out3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [11]:
out3.shape

torch.Size([2, 2, 3])

In [13]:
out4=torch.stack((a,b),dim=1)
out4

tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])

In [15]:
out4[:,0,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [16]:
out4[:,1,:]

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [19]:
out5=torch.stack((a,b),dim=2)
print(out5.shape)
out5

torch.Size([2, 3, 2])


tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])