In [1]:
import torch

In [7]:
a=torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
b=torch.cos(a)
b

tensor([[0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403]])

In [9]:
c=torch.zeros(2,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])